-- MySQL Script generated by MySQL Workbench
-- Fri Apr 13 17:50:29 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`flagella`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`flagella` (
  `alpha` INT UNSIGNED NOT NULL,
  `beta` INT UNSIGNED NOT NULL,
  `number` INT UNSIGNED NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`toughness`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`toughness` (
  `beta` INT UNSIGNED NOT NULL,
  `gamma` INT NOT NULL,
  `rank` CHAR NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`examined`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`examined` (
  `genotype` INT UNSIGNED NOT NULL,
  `class` VARCHAR(2) NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
